
# ansible-playbook -i inventarios/inventario1.yml playbooks/playbook_roles1.yaml
- hosts: ubuntu01
  remote_user: root
  
  vars:
    nginx_port: 81
    server_name: ubuntu01
    nginx_web_path: /web
  
  roles:
    - nginx